export const SUPPORTED_LANGUAGES = [
  { name: 'Arabic', value: 'ar' },
  { name: 'Bulgarian', value: 'bg' },
  { name: 'Chinese', value: 'zh' },
  { name: 'Croatian', value: 'hr' },
  { name: 'Czech', value: 'cs' },
  { name: 'Danish', value: 'da' },
  { name: 'Dutch', value: 'nl' },
  { name: 'English', value: 'en' },
  { name: 'Finnish', value: 'fi' },
  { name: 'French', value: 'fr' },
  { name: 'German', value: 'de' },
  { name: 'Greek', value: 'el' },
  { name: 'Hindi', value: 'hi' },
  { name: 'Hungarian', value: 'hu' },
  { name: 'Indonesian', value: 'id' },
  { name: 'Italian', value: 'it' },
  { name: 'Japanese', value: 'ja' },
  { name: 'Korean', value: 'ko' },
  { name: 'Malay', value: 'ms' },
  { name: 'Norwegian', value: 'no' },
  { name: 'Polish', value: 'pl' },
  { name: 'Portuguese (Brazil)', value: 'pt-br' },
  { name: 'Portuguese (Portugal)', value: 'pt' },
  { name: 'Romanian', value: 'ro' },
  { name: 'Russian', value: 'ru' },
  { name: 'Slovak', value: 'sk' },
  { name: 'Spanish', value: 'es' },
  { name: 'Swedish', value: 'sv' },
  { name: 'Tamil', value: 'ta' },
  { name: 'Turkish', value: 'tr' },
  { name: 'Ukrainian', value: 'uk' },
  { name: 'Vietnamese', value: 'vi' },
];

export const LLM_MODELS = [
  { name: 'Gemini 2.0 Flash', value: 'gemini-2.0-flash-001' },
  { name: 'Gemini 2.0 Flash Lite', value: 'gemini-2.0-flash-lite' },
  { name: 'Gemini 1.5 Flash', value: 'gemini-1.5-flash' },
  { name: 'Gemini 1.5 Pro', value: 'gemini-1.5-pro' },
  { name: 'Gemini 1.0 Pro', value: 'gemini-1.0-pro' },
  { name: 'GPT-4o Mini', value: 'gpt-4o-mini' },
  { name: 'GPT-4o', value: 'gpt-4o' },
  { name: 'GPT-4 Turbo', value: 'gpt-4-turbo' },
  { name: 'GPT-3.5 Turbo', value: 'gpt-3.5-turbo' },
  { name: 'Claude 3.7 Sonnet', value: 'claude-3-7-sonnet' },
  { name: 'Claude 3.5 Sonnet V2', value: 'claude-3-5-sonnet' },
  { name: 'Claude 3 Haiku', value: 'claude-3-haiku' },
];
