export const SUPPORTED_LANGUAGES = [
  { name: 'Arabic', value: 'ar' },
  { name: 'Bulgarian', value: 'bg' },
  { name: 'Chinese', value: 'zh' },
  { name: 'Croatian', value: 'hr' },
  { name: 'Czech', value: 'cs' },
  { name: 'Danish', value: 'da' },
  { name: 'Dutch', value: 'nl' },
  { name: 'English', value: 'en' },
  { name: 'Finnish', value: 'fi' },
  { name: 'French', value: 'fr' },
  { name: 'German', value: 'de' },
  { name: 'Greek', value: 'el' },
  { name: 'Hindi', value: 'hi' },
  { name: 'Hungarian', value: 'hu' },
  { name: 'Indonesian', value: 'id' },
  { name: 'Italian', value: 'it' },
  { name: 'Japanese', value: 'ja' },
  { name: 'Korean', value: 'ko' },
  { name: 'Malay', value: 'ms' },
  { name: 'Norwegian', value: 'no' },
  { name: 'Polish', value: 'pl' },
  { name: 'Portuguese (Brazil)', value: 'pt-br' },
  { name: 'Portuguese (Portugal)', value: 'pt' },
  { name: 'Romanian', value: 'ro' },
  { name: 'Russian', value: 'ru' },
  { name: 'Slovak', value: 'sk' },
  { name: 'Spanish', value: 'es' },
  { name: 'Swedish', value: 'sv' },
  { name: 'Tamil', value: 'ta' },
  { name: 'Turkish', value: 'tr' },
  { name: 'Ukrainian', value: 'uk' },
  { name: 'Vietnamese', value: 'vi' },
];

export const LLM_MODELS = [
  { name: 'Gemini 2.0 Flash', value: 'gemini-2.0-flash-001' },
  { name: 'Gemini 2.0 Pro', value: 'gemini-2.0-pro-001' },
  { name: 'Gemini 1.5 Pro', value: 'gemini-1.5-pro-001' },
  { name: 'Gemini 1.5 Flash', value: 'gemini-1.5-flash-001' },
  { name: 'Claude Opus', value: 'claude-3-opus-20240229' },
  { name: 'Claude Sonnet', value: 'claude-3-sonnet-20240229' },
  { name: 'Claude Haiku', value: 'claude-3-haiku-20240307' },
];
